### ISSUE TITLE
Try to move Image Scoring plugin to Python 3.10

### ISSUE THREAD

**Issue by joestubbs** [tapis-project/camera-traps#13]

**Comment by sowbaranika1302** [comment]
In order to upgrade the Image scoring plugin to Python 3.10, I made changes to the image-scoring file as tapis/image_scoring_plugin_py instead of tapis/image_scoring_plugin_py_3.8. After executing, I found an additional error message (Screenshot attached).

<img width="1026" alt="image" src="https://user-images.githubusercontent.com/109183136/230956388-291d7bdf-9840-4115-91e4-e71f79bf983b.png">


The current code reflects Image scoring with Python 3.10 to check if it gives the same error.

**Comment by khsa1** [comment]
@sowbaranika1302 Which branch/commit did you apply your python 3.10 changes to?

I am using branch  `main`, then modified `Makefile` and `releases/latest/docker-compose.yml` to use Dockerfile instead of `Dockerfile-3.8` to build `tapis/image_scoring_plugin_py`, but I get this error at runtime:
```
image_scoring            | Traceback (most recent call last):
image_scoring            |   File "image_scoring_plugin.py", line 14, in <module>
image_scoring            |     from camera_traps_MD.run_detector import load_and_run_detector
image_scoring            | ModuleNotFoundError: No module named 'camera_traps_MD'
image_scoring exited with code 1
```

**Comment by khsa1** [comment]
I was able to reproduce the `humanfriendly` error with `tapis/image_scoring_plugin_py`. In my image it looks like it's still using python 3.8 instead of python 3.10:

```
Python 3.8.10
pip 21.1.3 from /usr/local/lib/python3.8/site-packages/pip (python 3.8)
Package           Version
----------------- -------
asttokens         2.2.1
backcall          0.2.0
decorator         5.1.1
executing         1.2.0
flatbuffers       23.5.26
ipython           8.12.2
jedi              0.18.2
matplotlib-inline 0.1.6
parso             0.8.3
pexpect           4.8.0
pickleshare       0.7.5
pip               21.1.3
prompt-toolkit    3.0.38
ptyprocess        0.7.0
pure-eval         0.2.2
Pygments          2.15.1
pyzmq             25.0.0
setuptools        57.0.0
six               1.16.0
stack-data        0.6.2
traitlets         5.9.0
typing-extensions 4.7.0
wcwidth           0.2.6
wheel             0.36.2
zmq               0.0.0
WARNING: You are using pip version 21.1.3; however, version 23.1.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Traceback (most recent call last):
  File "image_scoring_plugin.py", line 14, in <module>
    from camera_traps_MD.run_detector import load_and_run_detector
  File "/camera_traps_MD/run_detector.py", line 10, in <module>
    import humanfriendly
ModuleNotFoundError: No module named 'humanfriendly'
```
